# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_auto_20160624_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
