# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0005_auto_20160624_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True, verbose_name='%m-%d-%Y'),
        ),
    ]
