# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0006_auto_20160624_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(),
        ),
    ]
