# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0007_auto_20160624_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bday',
        ),
    ]
